<template>
  <section class="page-container">
    <div class="welcome-row"><div><div class="eyebrow">MONDAY, SEPTEMBER 7, 2026</div><h1>早上好，林晓宇 <span>👋</span></h1><p>新学期已经开始，愿你选到心仪的课程。</p></div><RouterLink to="/courses" class="primary-btn"><Plus :size="18" /> 浏览课程</RouterLink></div>
    <div class="stats-grid"><article class="stat-card"><div class="stat-icon blue-bg"><BookOpen :size="20" /></div><div><span>本学期已选</span><strong>{{ store.selectedCourses.length }} <em>门课程</em></strong><small class="trend"><TrendingUp :size="13" />较上周 +2 门</small></div></article><article class="stat-card"><div class="stat-icon purple-bg"><Sparkles :size="20" /></div><div><span>已获得学分</span><strong>{{ store.selectedCredits }} <em>/ 18 学分</em></strong><small>本学期目标进度 {{ Math.min(100, Math.round((store.selectedCredits / 18) * 100)) }}%</small></div></article><article class="stat-card"><div class="stat-icon orange-bg"><Clock3 :size="20" /></div><div><span>本周课时</span><strong>{{ store.selectedCourses.length * 2 }} <em>课时</em></strong><small>分布在 {{ activeDays }} 个教学日</small></div></article><article class="stat-card"><div class="stat-icon green-bg"><CircleCheck :size="20" /></div><div><span>培养方案完成度</span><strong>{{ store.progress }}<em>%</em></strong><small>已修 {{ store.completedCredits }} / 54 学分</small></div></article></div>
    <div class="content-grid dashboard-grid"><section class="panel schedule-preview"><div class="panel-heading"><div><h2>本周课表</h2><p>2026 秋季学期 · 第 2 教学周</p></div><RouterLink to="/schedule" class="text-link">查看完整课表 <ArrowUpRight :size="15" /></RouterLink></div><div v-if="store.selectedCourses.length" class="mini-schedule"><div v-for="course in store.selectedCourses.slice(0, 4)" :key="course.id" class="mini-course" :class="`course-${course.color}`"><div class="mini-date">{{ course.dayLabel }}<b>{{ course.periods }}</b></div><div><strong>{{ course.name }}</strong><span>{{ course.periodLabel }} · {{ course.room }}</span></div></div></div><div v-else class="empty-state compact"><CalendarDays :size="28" /><strong>还没有选课</strong><span>去课程中心挑选本学期的第一门课吧</span><RouterLink to="/courses" class="text-link">马上选课 <ArrowUpRight :size="15" /></RouterLink></div></section><section class="panel progress-panel"><div class="panel-heading"><div><h2>学分进度</h2><p>距离本学期目标还有 {{ Math.max(0, 18 - store.selectedCredits) }} 学分</p></div><button class="more-btn" type="button">···</button></div><div class="progress-ring" :style="{ background: `conic-gradient(#507add 0 ${Math.round((store.selectedCredits / 18) * 100)}%, #e9eef8 ${Math.round((store.selectedCredits / 18) * 100)}% 100%)` }"><div class="ring-inner"><strong>{{ Math.round((store.selectedCredits / 18) * 100) }}<small>%</small></strong><span>已完成</span></div></div><div class="legend-list"><div v-for="item in creditLegend" :key="item.label"><i :class="item.class"></i><span>{{ item.label }}</span><strong>{{ item.value }} 学分</strong></div></div></section></div>
    <div class="content-grid lower-grid"><section class="panel"><div class="panel-heading"><div><h2>推荐课程</h2><p>根据你的专业方向精选</p></div><RouterLink to="/courses" class="text-link">查看全部 <ArrowUpRight :size="15" /></RouterLink></div><div class="recommend-list"><div v-for="course in recommendations" :key="course.id" class="recommend-item"><div class="course-badge" :class="`course-${course.color}`">{{ course.code.slice(0, 2) }}</div><div class="recommend-info"><strong>{{ course.name }}</strong><span>{{ course.teacher }} · {{ course.credits }} 学分 · {{ course.dayLabel }} {{ course.periods }} 节</span></div><button v-if="!store.isSelected(course.id)" class="ghost-btn" type="button" @click="choose(course)"><Plus :size="15" /> 选课</button><span v-else class="selected-label"><CircleCheck :size="15" /> 已选</span></div></div></section><section class="panel notice-panel"><div class="panel-heading"><div><h2>选课提醒</h2><p>请留意教务处最新通知</p></div><span class="notice-count">3</span></div><div class="notice-list"><div><i class="dot blue-dot"></i><p><strong>选课退改截止日期</strong><span>2026/09/18 23:59 前完成调整</span></p><ChevronRight :size="16" /></div><div><i class="dot orange-dot"></i><p><strong>专业必修课优先推荐</strong><span>先完成培养方案中的必修课程</span></p><ChevronRight :size="16" /></div><div><i class="dot purple-dot"></i><p><strong>课程容量实时更新</strong><span>部分热门课程名额有限</span></p><ChevronRight :size="16" /></div></div></section></div>
  </section>
</template>
<script setup>
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import { ArrowUpRight, CalendarDays, ChevronRight, CircleCheck, Clock3, BookOpen, Plus, Sparkles, TrendingUp } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import { useCourseStore } from '../stores'
const store = useCourseStore()
const activeDays = computed(() => new Set(store.selectedCourses.map((course) => course.weekday)).size)
const recommendations = computed(() => store.courses.filter((course) => ['CS101', 'FE308', 'DS301'].includes(course.id)))
const creditLegend = computed(() => [{ label: '专业必修', value: store.categoryStats.find((item) => item.name === '专业必修')?.value || 0, class: 'legend-blue' }, { label: '通识教育', value: store.categoryStats.find((item) => item.name === '通识教育')?.value || 0, class: 'legend-green' }, { label: '实践拓展', value: store.categoryStats.find((item) => item.name === '实践拓展')?.value || 0, class: 'legend-purple' }])
const choose = (course) => { const result = store.selectCourse(course); ElMessage({ type: result.ok ? 'success' : 'warning', message: result.message }) }
</script>

